# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('alt', models.CharField(max_length=255, verbose_name='Alt')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('img', models.FileField(blank=True, null=True, upload_to=b'banners', verbose_name='Image')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('sort', models.PositiveSmallIntegerField(default=500, verbose_name='Sort')),
                ('often', models.PositiveSmallIntegerField(choices=[[0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10]], help_text='A ten will display 10 times more often that a one.', verbose_name='Often')),
                ('html', models.BooleanField(default=False, verbose_name='Is HTML?')),
                ('flash', models.BooleanField(default=False, verbose_name='Is Flash?')),
                ('onlyauth', models.BooleanField(default=False, verbose_name='OnlyForAuth')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Is payed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'ordering': ['sort'],
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='BannerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('width', models.PositiveSmallIntegerField(default=0, verbose_name='Width')),
                ('height', models.PositiveSmallIntegerField(default=0, verbose_name='Height')),
                ('speed', models.PositiveSmallIntegerField(default=2000, verbose_name='Speed')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Banner Group',
                'verbose_name_plural': 'Banner Groups',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Clicked At')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=1024, null=True, verbose_name='User Agent')),
                ('page', models.URLField(blank=True, null=True, verbose_name='Page')),
                ('key', models.CharField(blank=True, max_length=32, null=True, verbose_name='User Agent')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, b'impressions'), (1, b'view'), (2, b'click')], default=0, max_length=1, verbose_name='Type')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_logs', to='banners.Banner')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_logs', to='banners.BannerGroup', verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='LogStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('view', models.PositiveIntegerField(verbose_name='Views')),
                ('click', models.PositiveIntegerField(verbose_name='Clicks')),
                ('unique_click', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unique Views')),
                ('unique_view', models.PositiveIntegerField(verbose_name='Unique Clicks')),
                ('banner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_stat', to='banners.Banner', verbose_name='Banner')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_stat', to='banners.BannerGroup', verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('url', models.CharField(max_length=2048, verbose_name='URL or URL RegEx')),
                ('regex', models.BooleanField(default=False, verbose_name='RegEx')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
        migrations.AddField(
            model_name='logstat',
            name='urls',
            field=models.ManyToManyField(blank=True, null=True, related_name='url_bloks', to='banners.URL', verbose_name='URLs'),
        ),
        migrations.AddField(
            model_name='log',
            name='urls',
            field=models.ManyToManyField(blank=True, related_name='url_logs', to='banners.URL', verbose_name='URLs'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='banner',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='banners.BannerGroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='banner',
            name='urls',
            field=models.ManyToManyField(blank=True, null=True, related_name='url_banners', to='banners.URL', verbose_name='URLs'),
        ),
    ]
