# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medtus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('anons', models.TextField(blank=True)),
                ('content', tinymce.models.HTMLField()),
                ('status', models.IntegerField()),
                ('createdate', models.DateTimeField(blank=True, null=True)),
                ('begindate', models.DateTimeField(blank=True, null=True)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment_cnt', models.IntegerField(blank=True, null=True)),
                ('comment_show', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('type', models.IntegerField()),
                ('format', models.IntegerField(blank=True, verbose_name='\u0424\u043e\u0440\u043c\u0430\u0442')),
                ('code', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('public_main', models.BooleanField(default=0, verbose_name='\u041f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u0442\u044c \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439')),
                ('spec_id', models.ForeignKey(blank=True, db_column=b'spec_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='medtus.Specialities', verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
                ('user_id', models.ForeignKey(db_column=b'user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a')),
            ],
            options={
                'db_table': 'Posts',
                'verbose_name': '\u041f\u043e\u0441\u0442',
                'verbose_name_plural': '\u041f\u043e\u0441\u0442\u044b',
            },
        ),
    ]
