# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medtus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('description', tinymce.models.HTMLField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('image', models.CharField(blank=True, max_length=255)),
                ('createdate', models.DateTimeField(blank=True, null=True)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('format', models.IntegerField(verbose_name='\u0424\u043e\u0440\u043c\u0430\u0442')),
                ('comment_cnt', models.IntegerField(blank=True, null=True)),
                ('comment_show', models.BooleanField(default=True)),
                ('popular', models.BooleanField(default=0)),
                ('show_cmedu', models.BooleanField(default=0)),
                ('show_medtus', models.BooleanField(default=1)),
                ('public_main', models.BooleanField(default=0)),
                ('spec_id', models.ForeignKey(db_column=b'spec_id', on_delete=django.db.models.deletion.CASCADE, to='medtus.Specialities')),
                ('user_id', models.ForeignKey(db_column=b'user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdate'],
                'db_table': 'Videos',
                'verbose_name': '\u0412\u0438\u0434\u0435\u043e \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u043b',
                'verbose_name_plural': '\u0412\u0438\u0434\u0435\u043e \u043c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='VideoStatistics',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Videos')),
            ],
            options={
                'db_table': 'videostatistics',
                'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u0440\u0430\u0437\u0434\u0435\u043b\u0430 \u0432\u0438\u0434\u0435\u043e',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430 \u0440\u0430\u0437\u0434\u0435\u043b\u0430 \u0432\u0438\u0434\u0435\u043e',
            },
        ),
    ]
