# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('password', models.CharField(blank=True, db_column=b'pass', max_length=128, null=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'last login')),
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('firstname', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name=b'email address')),
                ('avatar', models.FileField(blank=True, upload_to=b'profile_images')),
                ('sex', models.CharField(blank=True, max_length=256, null=True)),
                ('birthday', models.DateField(blank=True, max_length=256, null=True)),
                ('experience', models.CharField(blank=True, max_length=256, null=True)),
                ('addexperience', models.CharField(blank=True, max_length=256, null=True)),
                ('dissertation', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('addtitle', models.CharField(blank=True, max_length=256, null=True)),
                ('organization', models.CharField(blank=True, max_length=256, null=True)),
                ('job', models.CharField(blank=True, max_length=256, null=True)),
                ('site', models.CharField(blank=True, max_length=256, null=True)),
                ('school', models.CharField(blank=True, max_length=256, null=True)),
                ('graduate_year', models.CharField(blank=True, max_length=256, null=True)),
                ('faculty', models.CharField(blank=True, max_length=256, null=True)),
                ('cathedra', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_visible', models.CharField(blank=True, max_length=256, null=True)),
                ('email_visible', models.CharField(blank=True, max_length=256, null=True)),
                ('ICQ_Skype', models.CharField(blank=True, max_length=256, null=True)),
                ('social', models.CharField(blank=True, max_length=256, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('surname', models.CharField(max_length=256)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('lastvisit', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastaccess', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.IntegerField(blank=True, default=0, null=True)),
                ('user_ptr_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=b'user_image')),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AllMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgs', tinymce.models.HTMLField(blank=True, default=b'')),
                ('datetime', models.TextField(blank=True, default=b'')),
                ('type', models.PositiveSmallIntegerField(default=0)),
                ('unreaded', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Aword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('event_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PassToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('token', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0)),
            ],
        ),
    ]
