# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medtus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='country_id',
            field=models.ForeignKey(blank=True, db_column=b'country_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='medtus.Countries', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='events',
            name='spec_id',
            field=models.ForeignKey(blank=True, db_column=b'spec_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='medtus.Specialities', verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='events',
            name='town_id',
            field=models.ForeignKey(blank=True, db_column=b'town_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='medtus.Towns', verbose_name='\u0413\u043e\u0440\u043e\u0434'),
        ),
        migrations.AddField(
            model_name='events',
            name='user_id',
            field=models.ForeignKey(db_column=b'user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a'),
        ),
    ]
