# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('private', models.BooleanField(default=False, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xba\xd1\x80\xd1\x8b\xd1\x82\xd1\x8c \xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x86\xd1\x83')),
                ('page_alias', models.CharField(default=b'trs321', max_length=100, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('email_field', models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 email?')),
                ('phone_field', models.BooleanField(default=False, verbose_name='\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u043e\u043b\u0435 \u0442\u0435\u043b\u0435\u0444\u043e\u043d?')),
            ],
            options={
                'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
                'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('topic', models.CharField(max_length=255, verbose_name='\u0422\u0435\u043c\u0430 \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('contact', models.CharField(max_length=255, verbose_name='\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u043d\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435')),
                ('position', models.CharField(max_length=255, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('text', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043e\u0431\u0440\u0430\u0449\u0435\u043d\u0438\u044f')),
                ('answered', models.BooleanField(default=False, verbose_name='\u041e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043d\u043e')),
            ],
            options={
                'verbose_name': '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043e\u0431\u0440\u0430\u0442\u043d\u043e\u0439 \u0441\u0432\u044f\u0437\u0438',
                'verbose_name_plural': '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f \u043e\u0431\u0440\u0430\u0442\u043d\u043e\u0439 \u0441\u0432\u044f\u0437\u0438',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.IntegerField(blank=True, null=True)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialPhoto',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(upload_to=b'post_images')),
                ('thumb', models.ImageField(blank=True, upload_to=b'post_images')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialVideo',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('data', models.CharField(max_length=255)),
                ('preview', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostLinks',
            fields=[
                ('post_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('service_id', models.IntegerField(max_length=10)),
                ('object_id', models.IntegerField(max_length=10)),
                ('type', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'PostLinks',
            },
        ),
        migrations.CreateModel(
            name='PrivateContentPageUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='\u0424\u0418\u041e')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='phone')),
                ('city', models.CharField(max_length=255, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('speciality', models.CharField(max_length=255, verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtus.ContentPage', verbose_name='\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0430 \u043d\u0430 \u0434\u043e\u0441\u0442\u0443\u043f \u0441 popup',
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0430 \u043d\u0430 \u0434\u043e\u0441\u0442\u0443\u043f \u0441 popup',
            },
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('words', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'\xd0\xa1\xd0\xbf\xd0\xb8\xd1\x81\xd0\xbe\xd0\xba \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2 \xd1\x87\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb7 \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb1\xd0\xb5\xd0\xbb \xd0\xb4\xd0\xbb\xd1\x8f \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f rss')),
                ('passval', models.IntegerField(default=30, verbose_name=b'\xd0\xbf\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb3 \xd0\xb4\xd0\xbb\xd1\x8f \xd0\xb4\xd0\xb5\xd1\x82\xd0\xb5\xd0\xba\xd1\x82\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd1\x8f rss')),
                ('show', models.BooleanField(default=True, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7\xd1\x8b\xd0\xb2\xd0\xb0\xd1\x82\xd1\x8c \xd0\xb2 rss')),
            ],
            options={
                'db_table': 'Specialities',
                'verbose_name': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('material_id', models.IntegerField(blank=True, null=True)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('viewings', models.IntegerField(blank=True, null=True)),
                ('likes', models.TextField()),
            ],
            options={
                'db_table': 'statistics',
                'verbose_name': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430',
                'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430',
            },
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(db_index=True, default=1)),
                ('region', models.IntegerField(db_index=True)),
                ('order', models.IntegerField(default=65000)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('checked', models.IntegerField(db_index=True, default=1)),
                ('okrug', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Towns',
                'verbose_name': '\u0413\u043e\u0440\u043e\u0434',
                'verbose_name_plural': '\u0413\u043e\u0440\u043e\u0434\u0430',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='\u0422\u0440\u0430\u043d\u0441\u043b\u044f\u0446\u0438\u044f', max_length=255)),
                ('data_open', tinymce.models.HTMLField(blank=True, default=None, verbose_name='\u041e\u0442\u043a\u0440\u044b\u0442\u044b\u0435 \u0434\u0430\u043d\u043d\u044b\u0435')),
                ('data', tinymce.models.HTMLField(blank=True, default=None, verbose_name='\u0414\u0430\u043d\u043d\u044b\u0435')),
                ('begindate', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043d\u0430\u0447\u0430\u043b\u0430 \u0442\u0440\u0430\u043d\u0441\u043b\u044f\u0446\u0438\u0438')),
                ('enddate', models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043e\u043a\u043e\u043d\u0447\u0430\u043d\u0438\u044f \u0442\u0440\u0430\u043d\u0441\u043b\u044f\u0446\u0438\u0438')),
                ('is_accredited', models.BooleanField(default=0, verbose_name='\u0410\u043a\u043a\u0440\u0435\u0434\u0438\u0442\u043e\u0432\u0430\u043d \u041d\u041c\u041e')),
                ('checks_count', models.IntegerField(blank=True, default=0, verbose_name='\u041a\u043e\u043b-\u0432\u043e \u043f\u0440\u043e\u0432\u0435\u0440\u043e\u043a \u043f\u0440\u0438\u0441\u0443\u0442\u0441\u0442\u0432\u0438\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0435')),
                ('active', models.BooleanField(default=True, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u0422\u0440\u0430\u043d\u0441\u043b\u044f\u0446\u0438\u044f',
                'verbose_name_plural': '\u0422\u0440\u0430\u043d\u0441\u043b\u044f\u0446\u0438\u0438',
            },
        ),
        migrations.CreateModel(
            name='TranslationModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430 \u0438 \u0432\u0440\u0435\u043c\u044f \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0438')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtus.Translation')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationViewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checks_counter', models.IntegerField(default=0)),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtus.Translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dt_create'],
            },
        ),
        migrations.CreateModel(
            name='TranslationVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('dt_update', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medtus.Translation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dt_create'],
            },
        ),
        migrations.CreateModel(
            name='Visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.IntegerField(blank=True, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('lastview', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='towns',
            unique_together=set([('country_id', 'region', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='towns',
            index_together=set([('country_id', 'name')]),
        ),
    ]
