# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-02-21 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(db_index=True, default=1)),
                ('order', models.IntegerField(default=65000)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(null=True, blank=True, max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'db_table': 'Regions',
                'verbose_name': '\u0420\u0435\u0433\u0438\u043e\u043d',
                'verbose_name_plural': '\u0420\u0435\u0433\u0438\u043e\u043d\u044b',
            },
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ('id',), 'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0430', 'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u044b'},
        ),
        migrations.AlterField(
            model_name='postlinks',
            name='object_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postlinks',
            name='post_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlinks',
            name='service_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postlinks',
            name='type',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='towns',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='towns',
            index_together=set([]),
        ),
    ]
