# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-02-21 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medtus', '0003_create_regions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='towns',
            old_name='region',
            new_name='region_id',
        ),
        migrations.RemoveField(
            model_name='towns',
            name='country_id',
        ),
        migrations.AlterUniqueTogether(
            name='towns',
            unique_together=set([('region_id', 'name')]),
        ),
        migrations.AlterIndexTogether(
            name='towns',
            index_together=set([('region_id', 'name')]),
        ),
    ]
