# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(db_column=b'id', primary_key=True, serialize=False)),
                ('parent_id', models.IntegerField(null=True)),
                ('service_id', models.IntegerField(blank=True, null=True)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', tinymce.models.HTMLField()),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateTimeField(blank=True, null=True)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('content_type_id', models.IntegerField(blank=True, default=47, null=True)),
                ('safe', models.BooleanField(default=False, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7\xd1\x8b\xd0\xb2\xd0\xb0\xd1\x82\xd1\x8c \xd0\xba\xd0\xb0\xd0\xba HTML')),
                ('user_id', models.ForeignKey(db_column=b'user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Comments',
                'verbose_name': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439',
                'verbose_name_plural': '\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0438',
            },
        ),
    ]
