# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medtus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGalleries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', max_length=255)),
                ('description', models.TextField(db_column=b'description')),
                ('image', models.CharField(blank=True, db_column=b'image', max_length=255)),
                ('premoder', models.BooleanField(db_column=b'premoder')),
                ('status', models.BooleanField(db_column=b'status')),
                ('createdate', models.DateTimeField(auto_now_add=True, db_column=b'createdate')),
                ('public_main', models.BooleanField(default=0)),
                ('spec_id', models.ForeignKey(blank=True, db_column=b'spec_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='medtus.Specialities')),
                ('user', models.ForeignKey(db_column=b'user_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PGalleries',
            },
        ),
        migrations.CreateModel(
            name='PGPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column=b'title', max_length=255)),
                ('description', models.TextField(db_column=b'description')),
                ('image', models.FileField(blank=True, db_column=b'image', upload_to=b'pgphotos_images')),
                ('status', models.BooleanField(db_column=b'status')),
                ('createdate', models.DateTimeField(auto_now_add=True, db_column=b'createdate')),
                ('updatedate', models.DateTimeField(auto_now=True, db_column=b'updatedate')),
                ('comment_cnt', models.IntegerField(db_column=b'comment_cnt', default=0)),
                ('rating', models.IntegerField(db_column=b'rating', default=0)),
                ('votes', models.IntegerField(db_column=b'votes', default=0)),
                ('gallery', models.ForeignKey(db_column=b'pgallery_id', on_delete=django.db.models.deletion.CASCADE, to='photos.PGalleries')),
                ('user', models.ForeignKey(blank=True, db_column=b'user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PGPhotos',
            },
        ),
    ]
