from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^agreement/$', 'account.views.agreement', name='agreement'),
                       url(r'^register1/$', 'account.views.register1', name='register1'),
                       url(r'^register2/$', 'account.views.register2', name='register2'),
                       url(r'^register3/$', 'account.views.register3', name='register3'),
                       url(r'^register4/$', 'account.views.register4', name='register4'),
                       url(r'^allmsg/$', 'account.views.allmsg', name='allmsg'),
                       url(r'^allmsgs/$', 'account.views.allmsgs', name='allmsgs'),
                       url(r'^allmsgcodes/$', 'account.views.allmsgcodes', name='allmsgcodes'),
                       url(r'^login/$', 'account.views.user_login', name='login'),
                       url(r'^logout/$', 'account.views.user_logout', name='logout'),
                       url(r'^timer/$', 'account.ajax.timer', name='timer'),
                       url(r'^forgot/$', 'account.views.password_forgot', name='forgot'),
                       url(r'^changepassword/$', 'account.views.password_change', name='change'),
                       url(r'^changepassword/(?P<token>\w{24})/$', 'account.views.password_change', name='change'),
                       url(r'^avatarupload/(?P<sizex>\d+)/(?P<sizey>\d+)$', 'account.views.avatarupload',
                           name='avatarupload'),
                       url(r'^addimageupload/(?P<sizex>\d+)/(?P<sizey>\d+)$', 'account.views.addimageupload',
                           name='addimageupload'),
)
