# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medtus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('online', models.BooleanField(default=0, verbose_name='\u041e\u043d\u043b\u0430\u0439\u043d-\u0442\u0440\u0430\u043d\u0441\u043b\u044f\u0446\u0438\u044f')),
                ('agreement', tinymce.models.HTMLField(blank=True)),
                ('spam_report_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Email \xd0\xb4\xd0\xbb\xd1\x8f \xd0\xbe\xd1\x82\xd1\x87\xd0\xb5\xd1\x82\xd0\xbe\xd0\xb2 \xd0\xbe \xd1\x81\xd0\xbf\xd0\xb0\xd0\xbc\xd0\xb5')),
                ('spam_report_period', models.SmallIntegerField(choices=[(0, b'\xd0\xb7\xd0\xb0 \xd0\xb2\xd1\x81\xd0\xb5 \xd0\xb2\xd1\x80\xd0\xb5\xd0\xbc\xd1\x8f'), (1, b'\xd0\xb7\xd0\xb0 \xd0\xbf\xd1\x80\xd0\xbe\xd1\x88\xd0\xb5\xd0\xb4\xd1\x88\xd0\xb8\xd0\xb5 \xd1\x81\xd1\x83\xd1\x82\xd0\xba\xd0\xb8'), (7, b'\xd0\xb7\xd0\xb0 \xd0\xbf\xd1\x80\xd0\xbe\xd1\x88\xd0\xb5\xd0\xb4\xd1\x88\xd1\x83\xd1\x8e \xd0\xbd\xd0\xb5\xd0\xb4\xd0\xb5\xd0\xbb\xd1\x8e')], default=0, verbose_name=b'\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb8\xd0\xbe\xd0\xb4, \xd0\xb7\xd0\xb0 \xd0\xba\xd0\xbe\xd1\x82\xd0\xbe\xd1\x80\xd1\x8b\xd0\xb9 \xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd1\x8c \xd0\xbe\xd1\x82\xd1\x87\xd0\xb5\xd1\x82\xd1\x8b \xd0\xbe \xd1\x81\xd0\xbf\xd0\xb0\xd0\xbc\xd0\xb5')),
                ('translation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medtus.Translation')),
            ],
            options={
                'db_table': 'Settings',
                'verbose_name': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430 \u043f\u0440\u043e\u0435\u043a\u0442\u0430',
                'verbose_name_plural': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043f\u0440\u043e\u0435\u043a\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='SocialIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0439 \u0441\u0435\u0442\u0438')),
                ('icon', models.ImageField(upload_to=b'social_icons', verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430')),
                ('active', models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c')),
                ('url', models.URLField(verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u0443\u044e \u0441\u0435\u0442\u044c')),
            ],
            options={
                'verbose_name': '\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u0430\u044f \u0441\u0435\u0442\u044c',
                'verbose_name_plural': '\u0421\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u0441\u0435\u0442\u0438',
            },
        ),
    ]
