# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medtus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('url', models.CharField(max_length=200, verbose_name=b'url')),
                ('active', models.BooleanField(default=True, verbose_name=b'\xd0\x90\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xbd\xd0\xbe')),
            ],
            options={
                'db_table': 'rss_feeds',
                'verbose_name': 'Rss \u0441\u0442\u0440\u0438\u043c\u044b',
                'verbose_name_plural': 'Rss \u0441\u0442\u0440\u0438\u043c\u044b',
            },
        ),
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('words', models.CharField(max_length=250, verbose_name=b'\xd0\xa1\xd0\xbf\xd0\xb8\xd1\x81\xd0\xbe\xd0\xba \xd1\x81\xd0\xbb\xd0\xbe\xd0\xb2')),
                ('active', models.BooleanField(default=True, verbose_name=b'\xd0\x90\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xbd\xd0\xbe')),
                ('passval', models.IntegerField(default=30, verbose_name=b'\xd0\xbf\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb3')),
            ],
            options={
                'db_table': 'rss_filters',
                'verbose_name': '\u0424\u0438\u043b\u044c\u0442\u0440\u044b',
                'verbose_name_plural': '\u0424\u0438\u043b\u044c\u0442\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField()),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedate', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=250, verbose_name=b'\xd0\x97\xd0\xb0\xd0\xb3\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xba')),
                ('text', tinymce.models.HTMLField(max_length=250, verbose_name=b'\xd0\x9e\xd0\xbf\xd0\xb8\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5')),
                ('href', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'\xd0\xa1\xd1\x81\xd1\x8b\xd0\xbb\xd0\xba\xd0\xb0')),
                ('show', models.BooleanField(default=False, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xba\xd0\xb0\xd0\xb7\xd1\x8b\xd0\xb2\xd0\xb0\xd1\x82\xd1\x8c')),
                ('code', models.TextField(blank=True)),
                ('status', models.IntegerField(blank=True, null=True, verbose_name=b'\xd0\x90\xd0\xba\xd1\x82\xd0\xb8\xd0\xb2\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x8c')),
                ('image', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('popular', models.BooleanField(default=False)),
                ('format', models.IntegerField(verbose_name='\u0424\u043e\u0440\u043c\u0430\u0442')),
                ('comment_cnt', models.IntegerField(blank=True, null=True)),
                ('comment_show', models.BooleanField(default=True)),
                ('show_cmedu', models.BooleanField(default=0)),
                ('show_medtus', models.BooleanField(default=1)),
                ('public_main', models.BooleanField(default=0)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.Feeds')),
                ('spec_id', models.ForeignKey(blank=True, db_column=b'spec_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rss_post', to='medtus.Specialities', verbose_name=b'\xd0\x9a\xd0\xb0\xd1\x82\xd0\xb5\xd0\xb3\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u041f\u043e\u0441\u0442\u044b',
                'verbose_name_plural': '\u041f\u043e\u0441\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='feeds',
            name='filters',
            field=models.ManyToManyField(blank=True, null=True, to='rss.Filters', verbose_name=b'\xd0\xa4\xd0\xb8\xd0\xbb\xd1\x8c\xd1\x82\xd1\x80\xd1\x8b'),
        ),
    ]
