# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-10-11 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lecturers.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('surname', models.CharField(max_length=50, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('firstname', models.CharField(max_length=50, verbose_name='\u0418\u043c\u044f')),
                ('secondname', models.CharField(max_length=50, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('content', tinymce.models.HTMLField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(upload_to=lecturers.models.lecturer_img_file_name)),
                ('short_desc', models.TextField(verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
            options={
                'verbose_name': '\u041b\u0435\u043a\u0442\u043e\u0440',
                'verbose_name_plural': '\u041b\u0435\u043a\u0442\u043e\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='LecturerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430')),
                ('text', models.CharField(max_length=200, verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='lecturers.Lecturer')),
            ],
            options={
                'verbose_name': '\u041b\u0435\u043a\u0442\u043e\u0440-\u0421\u0441\u044b\u043b\u043a\u0430',
                'verbose_name_plural': '\u041b\u0435\u043a\u0442\u043e\u0440-\u0421\u0441\u044b\u043b\u043a\u0438',
            },
        ),
    ]
